### ISSUE TITLE
IMap Lock does not work in async/await scenarios

### ISSUE THREAD

**Issue by xbrabec** [hazelcast/hazelcast-csharp-client#221]
If I lock inside of an async method, calling some async operation between lock and unlock I can get an error: "Current thread is not owner of the lock".

In async methods, Unlock can be invoked on a different thread than corresponding Lock.

**Comment by stalek71** [comment]
Lock() and Unlock() operations use thread id (ManagedThreadId) as part of encoded message. When one thread locked the resource the other one has to wait until the lock has been released by the "owner" (so by thread with proper id whatever it is).
Async/await use so called continuations on awaiters so thread that continue execution of some code after await statement is randomly taken from the thread pool. So by definition Lock() thread and Unlock() thread differs when you use async/await.
There are a few options in such case:
- use ContinueWith() instead of async/await with  ExecuteSynchronously option (so both thread are the same),
- avoid using different threads between Lock() and Unlock().
Don't use ForceUnlock() untill you are 100% sure you know what are you doing. 
Some idea could be to let the user providing own "owner id" for lock/unlock operations.
This way we cross thread barrier when maintaining proper processing flow.
The current implementation of the client library doesn't support such feature at the moment.

**Comment by xbrabec** [comment]
Providing the "owner id" seems like a great idea to me.

Using threadId as a lock owner id makes the Hazelcast locking useless for most of the modern AspNet core applications I guess. (if not useless then prohibitively complicated to use for sure) 

Even if the "owner id" parameter is just an override to Lock and Unlock, with the default behavior to use threadId would be a great improvement.

**Comment by stalek71** [comment]
[This issue](https://github.com/hazelcast/hazelcast-csharp-client/issues/222) has been registered for such topic so I close the current one...
