### ISSUE TITLE
Reconnections in 4.0 [API-236]

### ISSUE THREAD

**Issue by andy-dev947** [hazelcast/hazelcast-csharp-client#429]
Hi

I just wanted to check what the expected behaviour is when the member a client is connected to is shutdown.  From my observations is seems that the client gets disconnected and will then never get reconnected again even if there are other members in the cluster still online.  The client just repeatedly throws ClientOfflineException.  The only way to recover seems to be to dispose the old client and then start a completely new connection using StartNewClientAsync.

If that is the case then what is the best way to detect when the client is in an unrecoverrable state? 

Also, I know the Java client can auto reconnect but I don't think this functionality works in the C# client even though the options are there?

Thanks

**Comment by zpqrtbnk** [comment]
Hey,

The current default behavior is indeed to shutdown the client when it gets disconnected. And then, yes, the client is lost and you have to start with an entirely new client. Handling the client `StateChanged` event would allow you do get notified when the state changes to `Disconnected`. However, the C# client *does* support the `options.Networking.ReconnectMode` setting that is `DoNotReconnect` by default, but can be changed to `ReconnectSync` or `ReconnectAsync` to obtain the functionality that you mention, where the client will auto-reconnect.

Note that, in the Java client, `ReconnectSync` blocks all invocations as long as the client has not reconnected, whereas `ReconnectAsync` keeps running the invocations (which then fail). The C# client at the moment only supports `ReconnectAsync`, i.e. the option to `ReconnectSync` setting has the same effect as `ReconnectAsync`. We plan to support `ReconnectSync` in a near future.

Hope this answers your question. Otherwise, feel free to ask again ;)

Cheers,
Stephan

**Comment by andy-dev947** [comment]
Hi,

I have tried setting ReconnectAsync but the client never reconnects again after I stop/start the cluster.

Code:
`options.Networking.ReconnectMode = ReconnectMode.ReconnectAsync;
options.Networking.ConnectionRetry.InitialBackoffMilliseconds = 1_000;
options.Networking.ConnectionRetry.MaxBackoffMilliseconds = 1_000;`

Exception:
`Hazelcast.Exceptions.ClientOfflineException: Hazelcast client is not connected.
   at Hazelcast.Clustering.ClusterMessaging.GetInvocationConnection(Invocation invocation)
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__9.MoveNext()`

Is there anything else I need to do?

Thanks,

**Comment by zpqrtbnk** [comment]
Not what I'd expect. You should definitively see some exceptions, while the cluster reconnects, but things should become stable again eventually. Running some tests here to check everything.

**Comment by andy-dev947** [comment]
Hi

Yeah I just had a map operation in a loop waiting to see it reconnect after I restarted the cluster but it never did.  I just received that exception continuously. 
I left it running for a few mins after the cluster started so it seemed like it was never going to recover.

Let me know if it works for you.

**Comment by zpqrtbnk** [comment]
reproduced, investigating both why it happens and how it escapes our tests

**Comment by zpqrtbnk** [comment]
cause identified, we have a fix, on it

**Comment by andy-dev947** [comment]
Thanks - the testing I have done suggests that the issue only happens with multiple members when you stop a members and it then goes into Shutdown state.  It seems after that any connections to the cluster after this will fail even though there are other members available.  It continues to fail even if the original member comes back online.  The only workaround seems to be to recreate the factory if any member gets shutdown

**Comment by andy-dev947** [comment]
Hi,

Is there any ETA for 4.0.2?

Thanks
