### ISSUE TITLE
A full queue doesn't throw exceptions - the PutAsync call just hangs

### ISSUE THREAD

**Issue by andy-dev947** [hazelcast/hazelcast-csharp-client#436]
Hi,

If I set a max-size on a queue and then try to put max-size + 1 items in it then I expect an exception to be thrown.

Instead the IQueue.PutAsync call just hangs (seemingly indefinitely).

```
var queue = await x.GetQueueAsync<string>("test-queue");

for (int i = 0; i < 1000; i++)
{
     //this line hangs when i = 100;
     await queue.PutAsync("test");
}
```

YAML:

```
queue:
 test-queue:
  max-size: 100
```

This is using Hazelcast 4.1.1.

Thanks,

**Comment by andy-dev947** [comment]
Actually - this might be by design.  If I use OfferAsync then it returns false after 100.  

I'm assuming that false can also be returned for other reasons.  In which case is there any way to determine if the reason an item was not able to be added was because the queue was full?

**Comment by zpqrtbnk** [comment]
When you `Put` something in the queue, it *has* to get in, so if the queue is full, the cluster waits for room in the queue. On the other hand, when you `Offer` something to the queue, the queue tries its best to accept your offer, but nicely warns you if it cannot, by returning false. So far, that is the behavior you are seeing.

As for determining whether your offer was rejected because the queue was full... as far as the *client* is concerned, all we get from the cluster is a boolean, not a reason. Of course you can immediately check the size of the queue but that will not give you an authoritative answer.

Let me ask the server guys whether they have a solution.

**Comment by zpqrtbnk** [comment]
Answer is: "*`false` always means one thing and it is: no space is currently available*".

For any other reason (unreachable cluster, etc) you'd get an exception.
Will update the documentation accordingly.

**Comment by andy-dev947** [comment]
Thanks!
