### ISSUE TITLE
Support for kubernetes (API) discovery

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#439]
Is support for discovery using the kubernetes API - similar to [hazelcast-kubernetes](https://github.com/hazelcast/hazelcast-kubernetes) - scheduled for the .NET client?
If yes, when can we expect this to be available?

**Comment by drieseng** [comment]
To clarify a little more:
We have a **Hazelcast** cluster running on **OpenShift** (which uses **K8s**), and a multi-node .NET application that runs on Windows.

Right now, the .NET application is configured to access **Hazelcast** as **unisocket client**.
This is clearly documented ([here](https://hazelcast.com/blog/how-to-set-up-your-own-on-premises-hazelcast-on-kubernetes/) to result in low performance.

Is work underway to support smart client in combination with **K8s** where the client is not running in **K8s**?
As far as I'm aware, this would require use of **Kubernetes API** to discover the cluster members.
However, the **Conclusion** section of the blog post - linked to above - mentions that other solutions are being worked on.

**Comment by zpqrtbnk** [comment]
Oh - never realized noone ever replied to this issue, while we were actually working on it! The Kubernetes discovery API which allows you to configure the Hazelcast client in Smart Routing mode (vs unisocket) is going to be supported in the upcoming v5 release of the client. No exact release date but we are talking weeks, not months.

**Comment by drieseng** [comment]
@zpqrtbnk Can you explain how we should configure the client to use the Kubernetes discovery API? In Java, you can specify the kubernete namespace and service name:
```java
config.getNetworkConfig().getJoin().getKubernetesConfig().setEnabled(true)
      .setProperty("namespace", "MY-KUBERNETES-NAMESPACE")
      .setProperty("service-name", "MY-SERVICE-NAME");
```

What's the corresponding .NET code?

**Comment by zpqrtbnk** [comment]
I am suddenly afraid there has been some confusion with this issue. All our tests, and all the work that has been done, ensure that one can connect to a Kubernetes cluster using the method described in the tutorials, i.e. connect to 1 entry point (can be a load-balanced pod) and then handle the members list received from the cluster. Our tests with running the client within the k8 environment worked the same. Sounded good at that time.

Now, from what I have learned about discovery since, plus reading docs... I realize the .NET client *still* does not implement the "Kubernetes API discovery" just as it does not implement AWS etc. Feeling silly now.

Guess we need to put it back onto our backlog?
