### ISSUE TITLE
IHazelcastClient.Members shows all members of the cluster

### ISSUE THREAD

**Issue by alisengul53** [hazelcast/hazelcast-csharp-client#453]
There is no way to find currenct connections of a client to members. IHazelcastClient.Members property shows all members not only connected ones for client. It would be better to show connected ones with this property.
There could be another property like IHazelcastClient.AllMembers and it can return all members of the cluster

**Comment by zpqrtbnk** [comment]
Have been facing this issue in tests, there is indeed no way to list connected members.

In fact, `IHazelcastClient.Members` returns the list of members as it was communicated by the cluster, regardless of whether members are connected or not, and that is not super-useful. I am considering modifying it to return members *and* whether they are connected or not.

Now, I don't want to modify `MemberInfo` (adding a `IsConnected` property) because it should remain an immutable thing, so I am thinking of returning a `ClientMemberInfo` instead:
```
public readonly struct ClientMemberInfo
{
  public MemberInfo Member { get; }
  public bool IsConnected { get; }
}
```

And then, changing the return type of `IHazelcastClient.Members` is a breaking change... will probably do it with v5.
