### ISSUE TITLE
No StateChange event fired (and Queue events at random)

### ISSUE THREAD

**Issue by aheintz** [hazelcast/hazelcast-csharp-client#466]
I'm trying to use `ItemAdded` to subscribe to when items added to a queue, but events are not consistently fired. I first thought it was due to includeValue=false but the subscription does not behave consistently despite includeValue=true.

I then tried to get the queue and add a subscriber to the queue after StateChange=>Connected, although that event is not fired in 4.0.1. In 4.0.2-preview.4 it is though. There's still some randomness into when queue item added is fired though.

**Comment by zpqrtbnk** [comment]
Just to be sure. You subscribe to the queue `ItemAdded` event, then you add items to the queue, and events are not consistently fired. Which, I assume, means that *some* items trigger an event, but not all of them, right?

Re. your second paragraph: which event "is not fired in 4.0.1"? How did you subscribe before doing what you describe?

**Comment by aheintz** [comment]
I subscribe to the queue `ItemAdded` events, and on some runs, events are not fired at all, and on some (but fewer) runs events are fired, I haven't been able to test using higher load, but when I'm able to subscribe, it seems to work.

The first problem I had (with version 4.0.1) was that no `StateChange=Connected` was fired at all. That is corrected in 4.0.2-preview.4. 

Below is an excerpt from my code, I get the feeling there's a timing issue somewhere, but I can't find a way to replicate it consistently. I'm no longer using queue subscription to trigger message polling, but doing it using a timer instead so I'm not blocked by the issue.

```
options.AddSubscriber(events =>
{
    events.StateChanged(async (cli, args) =>
    {
        if (args.State == ClientState.Connected)
        {
            Console.WriteLine("State == Connected");
            changeQueue = await cli.GetQueueAsync<ObjectChangedEvent>("MyQueue");
            await changeQueue.SubscribeAsync(handlers =>
            {
                handlers.ItemAdded((collection, qHandlers) => { Console.WriteLine("Received event"); });
            });
        }
    });
});

hazelcastClient = await HazelcastClientFactory.StartNewClientAsync(options);
```

**Comment by zpqrtbnk** [comment]
Hey.

I have spent some time on this issue and wrote a test for it which you can find in [this gist](https://gist.github.com/zpqrtbnk/07ca326fca1a0a77ed5fe56f59915a26) - and by this test, things work reliably all the time against our current `master` branch. We always get the state change event, always can subscribe to queue events, and always get all queue events. 

I understand you are now using a different approach, but would you be able to spend some time looking at the gist and telling me whether there is anything obvious you see that I may be missing? Otherwise I'll have to close the issue as "not reproducible".

Thanks!

**Comment by emreyigit** [comment]
not reproducible
