### ISSUE TITLE
Predicates.In not working for IEnumerable primary types.

### ISSUE THREAD

**Issue by jonashendrickx** [hazelcast/hazelcast-csharp-client#496]
Assume:
`
var array = new List<int>{ 1, 2, 3 };
var query = Predicates.In("fieldName", array);
`
This will not work, neither casting it to an array with `.ToArray<T>(IEnumerable<T> list)`

I get some kind of an exception that my array or object does not implement java.lang.Comparable.

Was able to work around is as follows
`
var list = new List<int>{ 1, 2, 3 };
var array = list.Cast<object>().ToArray();
var query = Predicates.In("fieldName", array);
`

I am writing my maps with key type 'string' and value type 'HazelcastJsonValue'.

**Comment by zpqrtbnk** [comment]
IIC you map is an `IHMap<string, HazelcastJsonValue>` i.e. keys are `string` objects, right? And then you query entries using a predicate, created with `Predicate.In("fieldname", values)` where `fieldname` is, I assume, the name of a JSON field? And... you get what I assume must be a remote protocol exception from the server?

Could you share a bit more code and maybe a copy of the exception stack trace to help use see through all this?
Which version is causing this issue exactly?
Thanks!

**Comment by zpqrtbnk** [comment]
Reproduced:
```
var result = await map.GetEntriesAsync(Predicates.In("fieldName", 1, 2, 3)); // this works
var result = await map.GetEntriesAsync(Predicates.In("fieldName", new List<int> { 1, 2, 3 })); // this fails
```
This is because the only overload we have for `Predicates.In` is:
```
public static IPredicate In(string name, params object[] values) { ... }
```
Which assumes that the list is the first `object` in the `values` arrays, and tries to serialize it and pass it to the server, which makes no sense. Fixing by adding an additional overload:
```
public static IPredicate In<T>(string name, IEnumerable<T> values) { ... }
```
which will be used whenever there's only 1 parameter beside `name` and that parameter is an `IEnumerable<T>` - we'll turn it into a collection of objects for the predicate to use.

Adding a test to validate this. Expect a PR soon.
