### ISSUE TITLE
Connection fallback on smart-routing mode [API-1398]

### ISSUE THREAD

**Issue by emreyigit** [hazelcast/hazelcast-csharp-client#612]
The client should fallback to received member list in case of connection failure to configured address when `SmartRouting=true`.

**Comment by drieseng** [comment]
@emreyigit Can you explain why you would want this? In our case, our members are not even accessible via their IP.

**Comment by emreyigit** [comment]
@drieseng sure. The situation depends on your usage actually. When `SmartRouting=true`, client connects to cluster with one of the members that are provided in options. Then, client receives the member list in the cluster. Then, connects to all of them. Until here everything is fine. When client disconnected from all members, it starts to reconnect by using provided addresses in options. User may not have to provide all member addresses in the cluster while configuring the client. So, client should also use the address list that is received from cluster during reconnection. This is a default behavior for other Hazelcast clients as well.

**Comment by drieseng** [comment]
@emreyigit, I understand. But this issue is about a fallback when `SmartRouting=false`. Why would you want the Hazelcast client to start reaching out to member addresses if you explicitly told the client NOT to do this.

We, for example, use Hazelcast as a distributed cache.  We actually want it to fail fast when the cluster is not reachable (or not in a healthy state) as that allows us to fetch the data from the actual data source instead.  We do not want a get or put to take ages because the Hazelcast client thinks it's beneficial to retry operations or attempt to reconnect.

We prefer a call to Hazelcast to fail within a 500 ms over having that same call succeed only after 5 seconds.

**Comment by emreyigit** [comment]
@drieseng as I said this will happen when `SmartRouting` is enabled. If not, client will only use the address that are provided on configuration during retry. Btw, off course I don't know the case but you may want to check out [MapLoader](https://docs.hazelcast.com/cloud/maploader-and-mapstore) to use Hazelcast as source of truth.

**Comment by drieseng** [comment]
The description of the issue mentions `SmartRouting=false`:

> The client should fallback to received member list in case of connection failure to configured address when SmartRouting=false.

Perhaps I misunderstood.

**Comment by emreyigit** [comment]
.Net client uses the member addresses during reconnection.
