### ISSUE TITLE
Update Port Guessing Approach. [API-1486]

### ISSUE THREAD

**Issue by emreyigit** [hazelcast/hazelcast-csharp-client#677]
The client chooses a random port between 5701,5702 and 5703 if the port is not configured. In order to decrease the delay in this case, 5701 should be first tried than alternatives can be picked randomly accordingly.

**Comment by zpqrtbnk** [comment]
Analysis / Documentation:

Addresses are provided by the `ClusterConnections` `GetClusterAddresses` method which returns the following addresses, with a filter to ensure that each address is returned only once:
* The address of each known member, optionally shuffled (true by default)
* The addresses provided by the `AddressProvider`, optionally shuffled (true by default)

The `ConfigurationAddressProviderSource` is the default `AddressProvider` source and it returns the addresses specified in the configuration. For each address:
* If the address specifies a port, the address is returned
* Otherwise, `NetworkingOptions.PortRange` addresses are created starting with `NetworkingOptions.DefaultPort`

What happens is... `ConfigurationAddressProviderSource` *does* create the addresses in order i.e. `host:5701`, `host:5702`, `host:5703` *but* then `GetClusterAddresses` shuffles them all and the 5701-5702-5703 order is not respected anymore.

Comparing to Java...

Connection takes place in `TcpClientConnectionManager` method `doConnectToCandidateCluster` which:
* Gets the list of current members, shuffle it if it must be shuffled, tries each address
* Tries each address from `getPossibleMemberAddresses(context.getAddressProvider())`

That `getPossibleMemberAddresses` method gets addresses from the address provider, but it gets *two* sets of addresses: *primary* and *secondary* addresses. Each set can then be shuffled, but the respective order of each set is maintained, so a secondary address *always* comes after a primary one -- this is what we don't have in .NET.

The set of corresponding primary and secondary addresses for one configured address (a string) is determined by `AddressHelper` `getSocketAddresses` method which, via a kinda convoluted mechanism, will essentially do the same port range expansion that we do in .NET, and return:
* The first address of the range as primary
* The rest as secondary

Conclusion: we have to align .NET code with Java by separating primary and secondary addresses.
