### ISSUE TITLE
Error executing SQL query using IN operator [API-2160]

### ISSUE THREAD

**Issue by federicocodo** [hazelcast/hazelcast-csharp-client#854]
I'm trying to execute a parameterized sql query using the IN operator, my query is very simple:
```sql
SELECT *
FROM map
WHERE columnName IN (?)
```
As a parameter I pass the Hazelcast client a simple merged list of structured strings like: 'value1', 'value2' but I get an error when running the Hazelcast client.

![image](https://github.com/hazelcast/hazelcast-csharp-client/assets/62144863/106889fc-3f3b-43da-b3d2-d7f2962bbc7c)

Update, I'm trying to debug to see what's happening and found out that it's caused because:

- the query shows more than one row and in my Hazelcast map one row is valued with double while the other is null;
- the hazelcast double class is trying to decode the frame that contains a null value and causes an exception.

Is possible to resolve?

**Comment by emreyigit** [comment]
Hey @federicocodo, 

Could you share your Hazelcast .Net version, the code snippet that you execute the query and your mapping details of the map? 
Also, I don't recall that Hazelcast supports `IN` in SQL. You can see the supported functions [here](https://docs.hazelcast.com/hazelcast/5.3/sql/select).

**Comment by federicocodo** [comment]
I'm using Hazelcast 5.3.0, the query i'm trying to execute it's the above one
```sql
SELECT *
FROM map
WHERE columnName IN (?)
```
The map it's saved in Hazelcast using the `HazelcastJsonValue`, I never had any problems until I tried to do the query and this it'snt a map problem.
I already looked and the documentation says that you can do queries using `IN`, [you can't just do subqueries only](https://docs.hazelcast.com/hazelcast/5.3/sql/functions-and-operators#in-operator).
I also opened the issue in the `Hazelcast` repository.

**Comment by emreyigit** [comment]
I meant the type mappings of the object in the map. For example, if value is `HazelcastJsonValue`, then you can't reach to `columnName` directly since it is the part of json value. In order to reach a field from json, you should use json [functions](https://docs.hazelcast.com/hazelcast/5.3/sql/functions-and-operators#json-functions).  If you provide more information about type mappings and consuming part of the query, I can try to reproduce the problem.

**Comment by federicocodo** [comment]
Oh sorry, the mapping is created as keyFormat = `varchar` and valueFormat = `json-flat`. It's strange because the column I'm trying to filter is inside the json map but I can filter it anyway without needing json functions when I'm using Hazelcast mancenter cause I use to verify that the queries worked and as you can see from the image it works and returns the correct results using a column present in the json mapping.
Apparently it can make the queries using the column present in the json only using Hazelcast mancenter while via code I have to use the filters on the json as you say.
As soon as I can I'll try to do this test using the json methods, thanks.

<img width="457" alt="image" src="https://github.com/hazelcast/hazelcast-csharp-client/assets/62144863/fb515ead-09dd-4e12-b5d9-70d549a67b59">

**Comment by emreyigit** [comment]
Hey @federicocodo, I'm able to reproduce the issue. Normally, you should get this error while reading the column with null value but some internal checks cause the problem in early stage. In MC, it also throws since column is null but it can be catch while reading. I'll keep this issue open to fix this bug. 

Thank you for the issue.
